name: Full Crypto CPR Scanner

on:
  schedule:
    - cron: '2 0 * * *'
  workflow_dispatch:

jobs:
  run-cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run CPR scan
        run: python main.py

