name: Daily CPR Scanner

on:
  schedule:
    - cron: '3 0 * * *'  # Runs at 00:03 UTC daily
  workflow_dispatch:

jobs:
  run-cpr-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CPR Scan
        run: python main.py
